version: '3.9'
services:
  react-app:
    build:
      context: ./client
    container_name: react-app-container
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build:
      context: ./server
    container_name: server-container
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
